Restrict-msg: "&a&l! >> &7This server is using %prefix%, &7you will need an &cAdmin &7to move!"
Inform-msg: "&a&l! >> &7You need an administrator to release you. &b&nUse /msg."
no-Permission: "%prefix%: &eSorry, you need permission to use this."
Admin-lock-msg: "&a&l! >> &7The user, &a&n%user% &r &7has been locked."
User-lock-msg: "&a&l! >> &7You have been &a&nLocked&r &7 by an Admin!"
Admin-unlock-msg: "&a&l! >> &7The user, &a&n%user% &r &7has been unlocked."
User-unlock-msg: "&a&l! >> &7You have been &a&nunlocked&r &7an Admin!"
Lock-API: true
Lock-API-off: "&a&l! >> %prefix% &7on user join is &cdisabled!"
Lock-API-on: "&a&l! >> %prefix% &7on user join is &aenabled!"