name: PlayerLock
main: me.ES359.com.PlayerLock
version: 0.1.2
description: Plugin allows you to restrict users from moving.
author: Signifies
website: https://www.spigotmc.org/members/signifies.40551/

commands:
  playerlock:
    description: Main command for the plugin.
    aliases: [lock, plock]